# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Valeriy Kurdyayev
title: QA Automation Engineer
email: adoafw@gmail.com


# Social links
#twitter_username: facespics
github_username:  artifexrefercio
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: valqa
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Val and I’m a <mark>QA Automation Engineer</mark> with 5 years of experiance. As well as QA I also have experience in Linux administrating and making software and web apps mostly with Python. I have worked at a number of companies gaining techicals as well as teamwork and leadership skills. My favorite stack for building test framework is <mark>Python</mark>, Pytest, <mark>Selenium</mark>, Allure, <mark>Appium</mark>(optional), ELK(optional). 


# Projects Section
# projects_title: Projects

# Experience Section
#experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in QA some of my other interests and hobbies are:
   - Gaming (PS4)
   - Playing Guitar and Singing
   - Swimming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed



